version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "unify-payment-stack"
region = "ap-south-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]

[default.deploy]
[default.deploy.parameters]
stack_name = "unify-payment-stack"
region = "ap-south-1"
resolve_s3 = true
s3_prefix = "unify-payment"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
confirm_changeset = true
no_fail_on_empty_changeset = true
parameter_overrides = []

[default.build]
[default.build.parameters]
use_container = false
